name: Build and Deploy .NET App Locally

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '4.6.1'  # Adjust to your version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish project
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to local folder
      run: |
        $destination = "E:\Angular Training"
        if (!(Test-Path $destination)) {
          New-Item -ItemType Directory -Path $destination
        }
        Copy-Item -Path "./publish/*" -Destination $destination -Recurse -Force
